apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato-clone
  template:
    metadata:
      labels:
        app: zomato-clone
    spec:
      containers:
      - name: zomato-clone
        image: <DOCKER-HUB-USERNAME>/zomato-clone:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-clone-svc
spec:
  type: LoadBalancer
  selector:
    app: zomato-clone
  ports:
  - port: 80
    targetPort: 3000
